//go:build ppc64le

package ascii

import "golang.org/x/sys/cpu"

// VSX kernels (16-byte stride) generated by go-asmgen (ascii_ppc64le_gen.go), in
// ascii_ppc64le.s. The kernels load and store blocks with LXVB16X/STXVB16X,
// ISA-3.0 (POWER9) instructions that raise SIGILL on POWER8, so they run only
// when hasVSX reports POWER9+; on POWER8 the *SIMD entry points report that they
// processed nothing and the scalar tails in ascii.go fold the whole slice.
func lowerBlocks(dst, src []byte, n int)
func upperBlocks(dst, src []byte, n int)
func equalFoldBlocks(a, b []byte, n int) int

// hasVSX is the dispatch flag. The generated kernels emit the ISA-3.0 (POWER9)
// LXVB16X/STXVB16X instructions, which are illegal on POWER8, so they are gated
// on POWER9 detection; on POWER8 every *SIMD function below returns 0 (no whole
// blocks consumed) and the scalar tails do all the work. It is a var (not a
// const) so the dispatch test can also drive the no-SIMD fallback on a POWER9+
// host.
var hasVSX = cpu.PPC64.IsPOWER9

func lowerSIMD(dst, src []byte) int {
	if n := len(src); hasVSX && n >= 16 {
		blocks := n / 16
		lowerBlocks(dst, src, blocks)
		return blocks * 16
	}
	return 0
}

func upperSIMD(dst, src []byte) int {
	if n := len(src); hasVSX && n >= 16 {
		blocks := n / 16
		upperBlocks(dst, src, blocks)
		return blocks * 16
	}
	return 0
}

func equalFoldSIMD(a, b []byte) int {
	if n := len(a); hasVSX && n >= 16 {
		blocks := n / 16
		if equalFoldBlocks(a, b, blocks) == 0 {
			return -1
		}
		return blocks * 16
	}
	return 0
}
