// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·lowerBlocks(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R3
	MOVD src_base+24(FP), R4
	MOVD n+48(FP), R5
	MOVD $loA_p<>+0(SB), R8
	LXVB16X (R0)(R8), VS52
	MOVD $hiZ_p<>+0(SB), R8
	LXVB16X (R0)(R8), VS53
	MOVD $c80_p<>+0(SB), R8
	LXVB16X (R0)(R8), VS54
	MOVD $c02_p<>+0(SB), R8
	LXVB16X (R0)(R8), VS55
	CMP R5, $0
	BEQ done
	MOVD $0, R6
loop:
	LXVB16X (R6)(R4), VS32
	VSUBUBM V0, V20, V1
	VAND V1, V22, V1
	VXOR V1, V22, V1
	VSUBUBM V0, V21, V2
	VAND V2, V22, V2
	VAND V2, V1, V2
	VSRB V2, V23, V2
	VADDUBM V2, V0, V0
	STXVB16X VS32, (R6)(R3)
	ADD $16, R6
	ADD $-1, R5
	CMP R5, $0
	BNE loop
done:
	RET

TEXT ·upperBlocks(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R3
	MOVD src_base+24(FP), R4
	MOVD n+48(FP), R5
	MOVD $loa_p<>+0(SB), R8
	LXVB16X (R0)(R8), VS52
	MOVD $hiz_p<>+0(SB), R8
	LXVB16X (R0)(R8), VS53
	MOVD $c80_p<>+0(SB), R8
	LXVB16X (R0)(R8), VS54
	MOVD $c02_p<>+0(SB), R8
	LXVB16X (R0)(R8), VS55
	CMP R5, $0
	BEQ done
	MOVD $0, R6
loop:
	LXVB16X (R6)(R4), VS32
	VSUBUBM V0, V20, V1
	VAND V1, V22, V1
	VXOR V1, V22, V1
	VSUBUBM V0, V21, V2
	VAND V2, V22, V2
	VAND V2, V1, V2
	VSRB V2, V23, V2
	VSUBUBM V0, V2, V0
	STXVB16X VS32, (R6)(R3)
	ADD $16, R6
	ADD $-1, R5
	CMP R5, $0
	BNE loop
done:
	RET

TEXT ·equalFoldBlocks(SB), NOSPLIT, $0-64
	MOVD a_base+0(FP), R3
	MOVD b_base+24(FP), R4
	MOVD n+48(FP), R5
	MOVD $loA_p<>+0(SB), R8
	LXVB16X (R0)(R8), VS52
	MOVD $hiZ_p<>+0(SB), R8
	LXVB16X (R0)(R8), VS53
	MOVD $c80_p<>+0(SB), R8
	LXVB16X (R0)(R8), VS54
	MOVD $c02_p<>+0(SB), R8
	LXVB16X (R0)(R8), VS55
	VXOR V24, V24, V24
	CMP R5, $0
	BEQ fdone
	MOVD $0, R6
floop:
	LXVB16X (R6)(R3), VS35
	VSUBUBM V3, V20, V1
	VAND V1, V22, V1
	VXOR V1, V22, V1
	VSUBUBM V3, V21, V2
	VAND V2, V22, V2
	VAND V2, V1, V2
	VSRB V2, V23, V2
	VADDUBM V2, V3, V3
	LXVB16X (R6)(R4), VS36
	VSUBUBM V4, V20, V1
	VAND V1, V22, V1
	VXOR V1, V22, V1
	VSUBUBM V4, V21, V2
	VAND V2, V22, V2
	VAND V2, V1, V2
	VSRB V2, V23, V2
	VADDUBM V2, V4, V4
	VXOR V3, V4, V3
	VOR V3, V24, V24
	ADD $16, R6
	ADD $-1, R5
	CMP R5, $0
	BNE floop
fdone:
	MFVSRD VS56, R7
	VSLDOI $8, V24, V24, V25
	MFVSRD VS57, R8
	OR R7, R8, R7
	MOVD $1, R9
	CMP R7, $0
	BEQ fret
	MOVD $0, R9
fret:
	MOVD R9, ret+56(FP)
	RET

DATA loA_p<>+0(SB)/1, $0x41
DATA loA_p<>+1(SB)/1, $0x41
DATA loA_p<>+2(SB)/1, $0x41
DATA loA_p<>+3(SB)/1, $0x41
DATA loA_p<>+4(SB)/1, $0x41
DATA loA_p<>+5(SB)/1, $0x41
DATA loA_p<>+6(SB)/1, $0x41
DATA loA_p<>+7(SB)/1, $0x41
DATA loA_p<>+8(SB)/1, $0x41
DATA loA_p<>+9(SB)/1, $0x41
DATA loA_p<>+10(SB)/1, $0x41
DATA loA_p<>+11(SB)/1, $0x41
DATA loA_p<>+12(SB)/1, $0x41
DATA loA_p<>+13(SB)/1, $0x41
DATA loA_p<>+14(SB)/1, $0x41
DATA loA_p<>+15(SB)/1, $0x41
GLOBL loA_p<>(SB), RODATA|NOPTR, $16

DATA hiZ_p<>+0(SB)/1, $0x5b
DATA hiZ_p<>+1(SB)/1, $0x5b
DATA hiZ_p<>+2(SB)/1, $0x5b
DATA hiZ_p<>+3(SB)/1, $0x5b
DATA hiZ_p<>+4(SB)/1, $0x5b
DATA hiZ_p<>+5(SB)/1, $0x5b
DATA hiZ_p<>+6(SB)/1, $0x5b
DATA hiZ_p<>+7(SB)/1, $0x5b
DATA hiZ_p<>+8(SB)/1, $0x5b
DATA hiZ_p<>+9(SB)/1, $0x5b
DATA hiZ_p<>+10(SB)/1, $0x5b
DATA hiZ_p<>+11(SB)/1, $0x5b
DATA hiZ_p<>+12(SB)/1, $0x5b
DATA hiZ_p<>+13(SB)/1, $0x5b
DATA hiZ_p<>+14(SB)/1, $0x5b
DATA hiZ_p<>+15(SB)/1, $0x5b
GLOBL hiZ_p<>(SB), RODATA|NOPTR, $16

DATA loa_p<>+0(SB)/1, $0x61
DATA loa_p<>+1(SB)/1, $0x61
DATA loa_p<>+2(SB)/1, $0x61
DATA loa_p<>+3(SB)/1, $0x61
DATA loa_p<>+4(SB)/1, $0x61
DATA loa_p<>+5(SB)/1, $0x61
DATA loa_p<>+6(SB)/1, $0x61
DATA loa_p<>+7(SB)/1, $0x61
DATA loa_p<>+8(SB)/1, $0x61
DATA loa_p<>+9(SB)/1, $0x61
DATA loa_p<>+10(SB)/1, $0x61
DATA loa_p<>+11(SB)/1, $0x61
DATA loa_p<>+12(SB)/1, $0x61
DATA loa_p<>+13(SB)/1, $0x61
DATA loa_p<>+14(SB)/1, $0x61
DATA loa_p<>+15(SB)/1, $0x61
GLOBL loa_p<>(SB), RODATA|NOPTR, $16

DATA hiz_p<>+0(SB)/1, $0x7b
DATA hiz_p<>+1(SB)/1, $0x7b
DATA hiz_p<>+2(SB)/1, $0x7b
DATA hiz_p<>+3(SB)/1, $0x7b
DATA hiz_p<>+4(SB)/1, $0x7b
DATA hiz_p<>+5(SB)/1, $0x7b
DATA hiz_p<>+6(SB)/1, $0x7b
DATA hiz_p<>+7(SB)/1, $0x7b
DATA hiz_p<>+8(SB)/1, $0x7b
DATA hiz_p<>+9(SB)/1, $0x7b
DATA hiz_p<>+10(SB)/1, $0x7b
DATA hiz_p<>+11(SB)/1, $0x7b
DATA hiz_p<>+12(SB)/1, $0x7b
DATA hiz_p<>+13(SB)/1, $0x7b
DATA hiz_p<>+14(SB)/1, $0x7b
DATA hiz_p<>+15(SB)/1, $0x7b
GLOBL hiz_p<>(SB), RODATA|NOPTR, $16

DATA c80_p<>+0(SB)/1, $0x80
DATA c80_p<>+1(SB)/1, $0x80
DATA c80_p<>+2(SB)/1, $0x80
DATA c80_p<>+3(SB)/1, $0x80
DATA c80_p<>+4(SB)/1, $0x80
DATA c80_p<>+5(SB)/1, $0x80
DATA c80_p<>+6(SB)/1, $0x80
DATA c80_p<>+7(SB)/1, $0x80
DATA c80_p<>+8(SB)/1, $0x80
DATA c80_p<>+9(SB)/1, $0x80
DATA c80_p<>+10(SB)/1, $0x80
DATA c80_p<>+11(SB)/1, $0x80
DATA c80_p<>+12(SB)/1, $0x80
DATA c80_p<>+13(SB)/1, $0x80
DATA c80_p<>+14(SB)/1, $0x80
DATA c80_p<>+15(SB)/1, $0x80
GLOBL c80_p<>(SB), RODATA|NOPTR, $16

DATA c02_p<>+0(SB)/1, $0x02
DATA c02_p<>+1(SB)/1, $0x02
DATA c02_p<>+2(SB)/1, $0x02
DATA c02_p<>+3(SB)/1, $0x02
DATA c02_p<>+4(SB)/1, $0x02
DATA c02_p<>+5(SB)/1, $0x02
DATA c02_p<>+6(SB)/1, $0x02
DATA c02_p<>+7(SB)/1, $0x02
DATA c02_p<>+8(SB)/1, $0x02
DATA c02_p<>+9(SB)/1, $0x02
DATA c02_p<>+10(SB)/1, $0x02
DATA c02_p<>+11(SB)/1, $0x02
DATA c02_p<>+12(SB)/1, $0x02
DATA c02_p<>+13(SB)/1, $0x02
DATA c02_p<>+14(SB)/1, $0x02
DATA c02_p<>+15(SB)/1, $0x02
GLOBL c02_p<>(SB), RODATA|NOPTR, $16

