// Package ascii is a SIMD fast path for ASCII case folding — ToUpper, ToLower
// and a case-insensitive EqualFold — that is byte- AND result-identical to the
// standard library for every input.
//
// The case transform itself uses no table and no multiply, only a vector
// compare, a logical AND and an add: for ToLower, every byte in the inclusive
// range 'A'..'Z' gets 0x20 added (mask = (b>='A') & (b<='Z'); b += mask&0x20);
// ToUpper is the symmetric subtraction over 'a'..'z'. That shape compiles to a
// real SIMD kernel on all six 64-bit Go targets (amd64 SSE2/AVX2, arm64 NEON,
// loong64 LSX, riscv64 RVV, ppc64le VSX, s390x vector facility), generated by
// go-asmgen — on plain `go build`, no cgo, no GOEXPERIMENT.
//
// Bytes >= 0x80 are not ASCII; the standard library's bytes.ToUpper/ToLower
// apply full Unicode case mapping to them. To stay byte-identical, an input that
// contains any byte >= 0x80 is handled entirely by the standard library and the
// SIMD path is skipped; pure-ASCII input (the overwhelmingly common case) takes
// the SIMD path and is identical to bytes.ToUpper/ToLower on that input.
// EqualFold is ASCII case-insensitive: it matches bytes.EqualFold exactly on
// ASCII input and is documented ASCII-only for bytes >= 0x80.
package ascii

import (
	"bytes"
	"encoding/binary"
)

// hasNonASCII reports whether b contains any byte >= 0x80. It checks eight bytes
// at a time by masking the high bit of each byte in a 64-bit word.
func hasNonASCII(b []byte) bool {
	const himask = 0x8080808080808080
	i := 0
	for ; i+8 <= len(b); i += 8 {
		if binary.LittleEndian.Uint64(b[i:])&himask != 0 {
			return true
		}
	}
	for ; i < len(b); i++ {
		if b[i] >= 0x80 {
			return true
		}
	}
	return false
}

// ToLower returns a new slice with every ASCII upper-case letter in b folded to
// lower case. The result is identical to bytes.ToLower(b): for pure-ASCII input
// the SIMD kernel produces it; if b holds any byte >= 0x80 the whole call is
// delegated to bytes.ToLower so the Unicode mapping matches exactly.
func ToLower(b []byte) []byte {
	if hasNonASCII(b) {
		return bytes.ToLower(b)
	}
	dst := make([]byte, len(b))
	n := lowerSIMD(dst, b)
	for ; n < len(b); n++ {
		c := b[n]
		if 'A' <= c && c <= 'Z' {
			c += 'a' - 'A'
		}
		dst[n] = c
	}
	return dst
}

// ToUpper returns a new slice with every ASCII lower-case letter in b folded to
// upper case, identical to bytes.ToUpper(b) (delegating to it for input that
// contains any byte >= 0x80).
func ToUpper(b []byte) []byte {
	if hasNonASCII(b) {
		return bytes.ToUpper(b)
	}
	dst := make([]byte, len(b))
	n := upperSIMD(dst, b)
	for ; n < len(b); n++ {
		c := b[n]
		if 'a' <= c && c <= 'z' {
			c -= 'a' - 'A'
		}
		dst[n] = c
	}
	return dst
}

// ToLowerString returns s with every ASCII upper-case letter folded to lower
// case, identical to strings.ToLower(s) for ASCII input (and to the Unicode
// mapping for input with bytes >= 0x80).
func ToLowerString(s string) string {
	return string(ToLower([]byte(s)))
}

// ToUpperString returns s with every ASCII lower-case letter folded to upper
// case, identical to strings.ToUpper(s) for ASCII input.
func ToUpperString(s string) string {
	return string(ToUpper([]byte(s)))
}

// EqualFold reports whether a and b are equal under ASCII case folding: 'A'..'Z'
// is treated as equal to 'a'..'z'. For pure-ASCII input it is identical to
// bytes.EqualFold(a, b). For input containing bytes >= 0x80 it is delegated to
// bytes.EqualFold so Unicode simple folding matches exactly.
func EqualFold(a, b []byte) bool {
	if len(a) != len(b) {
		// bytes.EqualFold can equate strings of different byte length only via
		// multi-byte Unicode folding; defer that to the standard library.
		return bytes.EqualFold(a, b)
	}
	if hasNonASCII(a) || hasNonASCII(b) {
		return bytes.EqualFold(a, b)
	}
	n := equalFoldSIMD(a, b)
	if n < 0 {
		return false
	}
	for ; n < len(a); n++ {
		if asciiLower(a[n]) != asciiLower(b[n]) {
			return false
		}
	}
	return true
}

// asciiLower folds a single ASCII byte to lower case.
func asciiLower(c byte) byte {
	if 'A' <= c && c <= 'Z' {
		c += 'a' - 'A'
	}
	return c
}
