// Code generated by go-asmgen. DO NOT EDIT.

//go:build riscv64

#include "textflag.h"

TEXT ·lowerBlocks(SB), NOSPLIT, $0-56
	MOV dst_base+0(FP), X5
	MOV src_base+24(FP), X6
	MOV n+48(FP), X7
	VSETVLI $16, E8, M1, TA, MA, X8
	MOV $64, X14
	MOV $90, X15
	MOV $0x20, X16
	BEQ X7, X0, done
loop:
	VLE8V (X6), V1
	VMSGTUVX X14, V1, V0
	VMSLEUVX X15, V1, V2
	VMANDMM V2, V0, V0
	VADDVX X16, V1, V0, V1
	VSE8V V1, (X5)
	ADD $16, X6, X6
	ADD $16, X5, X5
	ADD $-1, X7, X7
	BNE X7, X0, loop
done:
	RET

TEXT ·upperBlocks(SB), NOSPLIT, $0-56
	MOV dst_base+0(FP), X5
	MOV src_base+24(FP), X6
	MOV n+48(FP), X7
	VSETVLI $16, E8, M1, TA, MA, X8
	MOV $96, X14
	MOV $122, X15
	MOV $0x20, X16
	BEQ X7, X0, done
loop:
	VLE8V (X6), V1
	VMSGTUVX X14, V1, V0
	VMSLEUVX X15, V1, V2
	VMANDMM V2, V0, V0
	VSUBVX X16, V1, V0, V1
	VSE8V V1, (X5)
	ADD $16, X6, X6
	ADD $16, X5, X5
	ADD $-1, X7, X7
	BNE X7, X0, loop
done:
	RET

TEXT ·equalFoldBlocks(SB), NOSPLIT, $0-64
	MOV a_base+0(FP), X5
	MOV b_base+24(FP), X6
	MOV n+48(FP), X7
	VSETVLI $16, E8, M1, TA, MA, X8
	MOV $64, X14
	MOV $90, X15
	MOV $0x20, X16
	VXORVV V8, V8, V8
	BEQ X7, X0, fdone
floop:
	VLE8V (X5), V3
	VMSGTUVX X14, V3, V0
	VMSLEUVX X15, V3, V2
	VMANDMM V2, V0, V0
	VADDVX X16, V3, V0, V3
	VLE8V (X6), V4
	VMSGTUVX X14, V4, V0
	VMSLEUVX X15, V4, V2
	VMANDMM V2, V0, V0
	VADDVX X16, V4, V0, V4
	VXORVV V4, V3, V3
	VORVV V3, V8, V8
	ADD $16, X5, X5
	ADD $16, X6, X6
	ADD $-1, X7, X7
	BNE X7, X0, floop
fdone:
	VMSNEVI $0, V8, V0
	VCPOPM V0, X10
	MOV $1, X11
	BEQ X10, X0, fret
	MOV $0, X11
fret:
	MOV X11, ret+56(FP)
	RET

