//go:build amd64

package ascii

import "golang.org/x/sys/cpu"

// SSE2 (16-byte) and AVX2 (32-byte) kernels generated by go-asmgen
// (ascii_amd64_gen.go), in ascii_amd64.s. Each transforms whole blocks of n
// source bytes into dst; lower folds 'A'..'Z'->+0x20, upper folds 'a'..'z'->-0x20.
func lowerBlocksSSE(dst, src []byte, n int)
func upperBlocksSSE(dst, src []byte, n int)
func lowerBlocksAVX2(dst, src []byte, n int)
func upperBlocksAVX2(dst, src []byte, n int)

// equalFoldBlocks{SSE,AVX2} fold both inputs and compare; they return 1 if all n
// blocks matched, 0 if some block differed.
func equalFoldBlocksSSE(a, b []byte, n int) int
func equalFoldBlocksAVX2(a, b []byte, n int) int

var hasAVX2 = cpu.X86.HasAVX2

// lowerSIMD folds whole blocks with the widest available kernel and returns the
// number of bytes processed; the caller folds the < stride tail.
func lowerSIMD(dst, src []byte) int {
	n := len(src)
	if hasAVX2 && n >= 32 {
		blocks := n / 32
		lowerBlocksAVX2(dst, src, blocks)
		return blocks * 32
	}
	if n >= 16 {
		blocks := n / 16
		lowerBlocksSSE(dst, src, blocks)
		return blocks * 16
	}
	return 0
}

func upperSIMD(dst, src []byte) int {
	n := len(src)
	if hasAVX2 && n >= 32 {
		blocks := n / 32
		upperBlocksAVX2(dst, src, blocks)
		return blocks * 32
	}
	if n >= 16 {
		blocks := n / 16
		upperBlocksSSE(dst, src, blocks)
		return blocks * 16
	}
	return 0
}

// equalFoldSIMD folds and compares whole blocks. It returns the number of bytes
// confirmed equal (a multiple of the stride) for the caller's tail to continue,
// or -1 if a block differed.
func equalFoldSIMD(a, b []byte) int {
	n := len(a)
	if hasAVX2 && n >= 32 {
		blocks := n / 32
		if equalFoldBlocksAVX2(a, b, blocks) == 0 {
			return -1
		}
		return blocks * 32
	}
	if n >= 16 {
		blocks := n / 16
		if equalFoldBlocksSSE(a, b, blocks) == 0 {
			return -1
		}
		return blocks * 16
	}
	return 0
}
