// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·lowerBlocks(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R2
	MOVD $loA<>+0(SB), R5
	VLD1 (R5), [V20.B16]
	MOVD $hiZ<>+0(SB), R5
	VLD1 (R5), [V21.B16]
	MOVD $c80<>+0(SB), R5
	VLD1 (R5), [V22.B16]
	CBZ R2, done
loop:
	VLD1 (R1), [V0.B16]
	VSUB V20.B16, V0.B16, V1.B16
	VAND V22.B16, V1.B16, V1.B16
	VEOR V22.B16, V1.B16, V1.B16
	VSUB V21.B16, V0.B16, V2.B16
	VAND V22.B16, V2.B16, V2.B16
	VAND V1.B16, V2.B16, V2.B16
	VUSHR $2, V2.B16, V2.B16
	VADD V2.B16, V0.B16, V0.B16
	VST1 [V0.B16], (R0)
	ADD $16, R1, R1
	ADD $16, R0, R0
	SUB $1, R2, R2
	CBNZ R2, loop
done:
	RET

TEXT ·upperBlocks(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R2
	MOVD $loa<>+0(SB), R5
	VLD1 (R5), [V20.B16]
	MOVD $hiz<>+0(SB), R5
	VLD1 (R5), [V21.B16]
	MOVD $c80<>+0(SB), R5
	VLD1 (R5), [V22.B16]
	CBZ R2, done
loop:
	VLD1 (R1), [V0.B16]
	VSUB V20.B16, V0.B16, V1.B16
	VAND V22.B16, V1.B16, V1.B16
	VEOR V22.B16, V1.B16, V1.B16
	VSUB V21.B16, V0.B16, V2.B16
	VAND V22.B16, V2.B16, V2.B16
	VAND V1.B16, V2.B16, V2.B16
	VUSHR $2, V2.B16, V2.B16
	VSUB V2.B16, V0.B16, V0.B16
	VST1 [V0.B16], (R0)
	ADD $16, R1, R1
	ADD $16, R0, R0
	SUB $1, R2, R2
	CBNZ R2, loop
done:
	RET

TEXT ·equalFoldBlocks(SB), NOSPLIT, $0-64
	MOVD a_base+0(FP), R0
	MOVD b_base+24(FP), R1
	MOVD n+48(FP), R2
	MOVD $loA<>+0(SB), R5
	VLD1 (R5), [V20.B16]
	MOVD $hiZ<>+0(SB), R5
	VLD1 (R5), [V21.B16]
	MOVD $c80<>+0(SB), R5
	VLD1 (R5), [V22.B16]
	VEOR V23.B16, V23.B16, V23.B16
	CBZ R2, fdone
floop:
	VLD1 (R0), [V3.B16]
	VSUB V20.B16, V3.B16, V1.B16
	VAND V22.B16, V1.B16, V1.B16
	VEOR V22.B16, V1.B16, V1.B16
	VSUB V21.B16, V3.B16, V2.B16
	VAND V22.B16, V2.B16, V2.B16
	VAND V1.B16, V2.B16, V2.B16
	VUSHR $2, V2.B16, V2.B16
	VADD V2.B16, V3.B16, V3.B16
	VLD1 (R1), [V4.B16]
	VSUB V20.B16, V4.B16, V1.B16
	VAND V22.B16, V1.B16, V1.B16
	VEOR V22.B16, V1.B16, V1.B16
	VSUB V21.B16, V4.B16, V2.B16
	VAND V22.B16, V2.B16, V2.B16
	VAND V1.B16, V2.B16, V2.B16
	VUSHR $2, V2.B16, V2.B16
	VADD V2.B16, V4.B16, V4.B16
	VEOR V4.B16, V3.B16, V3.B16
	VORR V3.B16, V23.B16, V23.B16
	ADD $16, R0, R0
	ADD $16, R1, R1
	SUB $1, R2, R2
	CBNZ R2, floop
fdone:
	VMOV V23.D[0], R3
	VMOV V23.D[1], R4
	ORR R4, R3, R3
	MOVD $0, R5
	CBNZ R3, fret
	MOVD $1, R5
fret:
	MOVD R5, ret+56(FP)
	RET

DATA loA<>+0(SB)/1, $0x41
DATA loA<>+1(SB)/1, $0x41
DATA loA<>+2(SB)/1, $0x41
DATA loA<>+3(SB)/1, $0x41
DATA loA<>+4(SB)/1, $0x41
DATA loA<>+5(SB)/1, $0x41
DATA loA<>+6(SB)/1, $0x41
DATA loA<>+7(SB)/1, $0x41
DATA loA<>+8(SB)/1, $0x41
DATA loA<>+9(SB)/1, $0x41
DATA loA<>+10(SB)/1, $0x41
DATA loA<>+11(SB)/1, $0x41
DATA loA<>+12(SB)/1, $0x41
DATA loA<>+13(SB)/1, $0x41
DATA loA<>+14(SB)/1, $0x41
DATA loA<>+15(SB)/1, $0x41
GLOBL loA<>(SB), RODATA|NOPTR, $16

DATA hiZ<>+0(SB)/1, $0x5b
DATA hiZ<>+1(SB)/1, $0x5b
DATA hiZ<>+2(SB)/1, $0x5b
DATA hiZ<>+3(SB)/1, $0x5b
DATA hiZ<>+4(SB)/1, $0x5b
DATA hiZ<>+5(SB)/1, $0x5b
DATA hiZ<>+6(SB)/1, $0x5b
DATA hiZ<>+7(SB)/1, $0x5b
DATA hiZ<>+8(SB)/1, $0x5b
DATA hiZ<>+9(SB)/1, $0x5b
DATA hiZ<>+10(SB)/1, $0x5b
DATA hiZ<>+11(SB)/1, $0x5b
DATA hiZ<>+12(SB)/1, $0x5b
DATA hiZ<>+13(SB)/1, $0x5b
DATA hiZ<>+14(SB)/1, $0x5b
DATA hiZ<>+15(SB)/1, $0x5b
GLOBL hiZ<>(SB), RODATA|NOPTR, $16

DATA loa<>+0(SB)/1, $0x61
DATA loa<>+1(SB)/1, $0x61
DATA loa<>+2(SB)/1, $0x61
DATA loa<>+3(SB)/1, $0x61
DATA loa<>+4(SB)/1, $0x61
DATA loa<>+5(SB)/1, $0x61
DATA loa<>+6(SB)/1, $0x61
DATA loa<>+7(SB)/1, $0x61
DATA loa<>+8(SB)/1, $0x61
DATA loa<>+9(SB)/1, $0x61
DATA loa<>+10(SB)/1, $0x61
DATA loa<>+11(SB)/1, $0x61
DATA loa<>+12(SB)/1, $0x61
DATA loa<>+13(SB)/1, $0x61
DATA loa<>+14(SB)/1, $0x61
DATA loa<>+15(SB)/1, $0x61
GLOBL loa<>(SB), RODATA|NOPTR, $16

DATA hiz<>+0(SB)/1, $0x7b
DATA hiz<>+1(SB)/1, $0x7b
DATA hiz<>+2(SB)/1, $0x7b
DATA hiz<>+3(SB)/1, $0x7b
DATA hiz<>+4(SB)/1, $0x7b
DATA hiz<>+5(SB)/1, $0x7b
DATA hiz<>+6(SB)/1, $0x7b
DATA hiz<>+7(SB)/1, $0x7b
DATA hiz<>+8(SB)/1, $0x7b
DATA hiz<>+9(SB)/1, $0x7b
DATA hiz<>+10(SB)/1, $0x7b
DATA hiz<>+11(SB)/1, $0x7b
DATA hiz<>+12(SB)/1, $0x7b
DATA hiz<>+13(SB)/1, $0x7b
DATA hiz<>+14(SB)/1, $0x7b
DATA hiz<>+15(SB)/1, $0x7b
GLOBL hiz<>(SB), RODATA|NOPTR, $16

DATA c80<>+0(SB)/1, $0x80
DATA c80<>+1(SB)/1, $0x80
DATA c80<>+2(SB)/1, $0x80
DATA c80<>+3(SB)/1, $0x80
DATA c80<>+4(SB)/1, $0x80
DATA c80<>+5(SB)/1, $0x80
DATA c80<>+6(SB)/1, $0x80
DATA c80<>+7(SB)/1, $0x80
DATA c80<>+8(SB)/1, $0x80
DATA c80<>+9(SB)/1, $0x80
DATA c80<>+10(SB)/1, $0x80
DATA c80<>+11(SB)/1, $0x80
DATA c80<>+12(SB)/1, $0x80
DATA c80<>+13(SB)/1, $0x80
DATA c80<>+14(SB)/1, $0x80
DATA c80<>+15(SB)/1, $0x80
GLOBL c80<>(SB), RODATA|NOPTR, $16

