// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·lowerBlocksSSE(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	MOVOU loA<>+0(SB), X5
	MOVOU hiZ<>+0(SB), X6
	MOVOU c20<>+0(SB), X7
	TESTQ CX, CX
	JZ done
loop:
	MOVOU (SI), X0
	MOVO X0, X1
	PCMPGTB X5, X1
	MOVO X6, X2
	PCMPGTB X0, X2
	PAND X2, X1
	PAND X7, X1
	PADDB X1, X0
	MOVOU X0, (DI)
	ADDQ $16, SI
	ADDQ $16, DI
	DECQ CX
	JNZ loop
done:
	RET

TEXT ·upperBlocksSSE(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	MOVOU loa<>+0(SB), X5
	MOVOU hiz<>+0(SB), X6
	MOVOU c20<>+0(SB), X7
	TESTQ CX, CX
	JZ done
loop:
	MOVOU (SI), X0
	MOVO X0, X1
	PCMPGTB X5, X1
	MOVO X6, X2
	PCMPGTB X0, X2
	PAND X2, X1
	PAND X7, X1
	PSUBB X1, X0
	MOVOU X0, (DI)
	ADDQ $16, SI
	ADDQ $16, DI
	DECQ CX
	JNZ loop
done:
	RET

TEXT ·lowerBlocksAVX2(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VMOVDQU loAb<>+0(SB), Y5
	VMOVDQU hiZb<>+0(SB), Y6
	VMOVDQU c20b<>+0(SB), Y7
	TESTQ CX, CX
	JZ vdone
vloop:
	VMOVDQU (SI), Y0
	VPCMPGTB Y5, Y0, Y1
	VPCMPGTB Y0, Y6, Y2
	VPAND Y2, Y1, Y1
	VPAND Y7, Y1, Y1
	VPADDB Y1, Y0, Y0
	VMOVDQU Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	DECQ CX
	JNZ vloop
vdone:
	VZEROUPPER
	RET

TEXT ·upperBlocksAVX2(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VMOVDQU loab<>+0(SB), Y5
	VMOVDQU hizb<>+0(SB), Y6
	VMOVDQU c20b<>+0(SB), Y7
	TESTQ CX, CX
	JZ vdone
vloop:
	VMOVDQU (SI), Y0
	VPCMPGTB Y5, Y0, Y1
	VPCMPGTB Y0, Y6, Y2
	VPAND Y2, Y1, Y1
	VPAND Y7, Y1, Y1
	VPSUBB Y1, Y0, Y0
	VMOVDQU Y0, (DI)
	ADDQ $32, SI
	ADDQ $32, DI
	DECQ CX
	JNZ vloop
vdone:
	VZEROUPPER
	RET

TEXT ·equalFoldBlocksSSE(SB), NOSPLIT, $0-64
	MOVQ a_base+0(FP), DI
	MOVQ b_base+24(FP), SI
	MOVQ n+48(FP), CX
	MOVOU loA<>+0(SB), X5
	MOVOU hiZ<>+0(SB), X6
	MOVOU c20<>+0(SB), X7
	PXOR X8, X8
	TESTQ CX, CX
	JZ fdone
floop:
	MOVOU (DI), X0
	MOVO X0, X3
	PCMPGTB X5, X3
	MOVO X6, X4
	PCMPGTB X0, X4
	PAND X4, X3
	PAND X7, X3
	PADDB X3, X0
	MOVOU (SI), X1
	MOVO X1, X3
	PCMPGTB X5, X3
	MOVO X6, X4
	PCMPGTB X1, X4
	PAND X4, X3
	PAND X7, X3
	PADDB X3, X1
	PXOR X1, X0
	POR X0, X8
	ADDQ $16, DI
	ADDQ $16, SI
	DECQ CX
	JNZ floop
fdone:
	XORQ AX, AX
	PTEST X8, X8
	SETEQ AL
	MOVQ AX, ret+56(FP)
	RET

TEXT ·equalFoldBlocksAVX2(SB), NOSPLIT, $0-64
	MOVQ a_base+0(FP), DI
	MOVQ b_base+24(FP), SI
	MOVQ n+48(FP), CX
	VMOVDQU loAb<>+0(SB), Y5
	VMOVDQU hiZb<>+0(SB), Y6
	VMOVDQU c20b<>+0(SB), Y7
	VPXOR Y8, Y8, Y8
	TESTQ CX, CX
	JZ vfdone
vfloop:
	VMOVDQU (DI), Y0
	VPCMPGTB Y5, Y0, Y3
	VPCMPGTB Y0, Y6, Y4
	VPAND Y4, Y3, Y3
	VPAND Y7, Y3, Y3
	VPADDB Y3, Y0, Y0
	VMOVDQU (SI), Y1
	VPCMPGTB Y5, Y1, Y3
	VPCMPGTB Y1, Y6, Y4
	VPAND Y4, Y3, Y3
	VPAND Y7, Y3, Y3
	VPADDB Y3, Y1, Y1
	VPXOR Y1, Y0, Y0
	VPOR Y0, Y8, Y8
	ADDQ $32, DI
	ADDQ $32, SI
	DECQ CX
	JNZ vfloop
vfdone:
	XORQ AX, AX
	VPTEST Y8, Y8
	SETEQ AL
	VZEROUPPER
	MOVQ AX, ret+56(FP)
	RET

DATA loA<>+0(SB)/1, $0x40
DATA loA<>+1(SB)/1, $0x40
DATA loA<>+2(SB)/1, $0x40
DATA loA<>+3(SB)/1, $0x40
DATA loA<>+4(SB)/1, $0x40
DATA loA<>+5(SB)/1, $0x40
DATA loA<>+6(SB)/1, $0x40
DATA loA<>+7(SB)/1, $0x40
DATA loA<>+8(SB)/1, $0x40
DATA loA<>+9(SB)/1, $0x40
DATA loA<>+10(SB)/1, $0x40
DATA loA<>+11(SB)/1, $0x40
DATA loA<>+12(SB)/1, $0x40
DATA loA<>+13(SB)/1, $0x40
DATA loA<>+14(SB)/1, $0x40
DATA loA<>+15(SB)/1, $0x40
GLOBL loA<>(SB), RODATA|NOPTR, $16

DATA hiZ<>+0(SB)/1, $0x5b
DATA hiZ<>+1(SB)/1, $0x5b
DATA hiZ<>+2(SB)/1, $0x5b
DATA hiZ<>+3(SB)/1, $0x5b
DATA hiZ<>+4(SB)/1, $0x5b
DATA hiZ<>+5(SB)/1, $0x5b
DATA hiZ<>+6(SB)/1, $0x5b
DATA hiZ<>+7(SB)/1, $0x5b
DATA hiZ<>+8(SB)/1, $0x5b
DATA hiZ<>+9(SB)/1, $0x5b
DATA hiZ<>+10(SB)/1, $0x5b
DATA hiZ<>+11(SB)/1, $0x5b
DATA hiZ<>+12(SB)/1, $0x5b
DATA hiZ<>+13(SB)/1, $0x5b
DATA hiZ<>+14(SB)/1, $0x5b
DATA hiZ<>+15(SB)/1, $0x5b
GLOBL hiZ<>(SB), RODATA|NOPTR, $16

DATA loa<>+0(SB)/1, $0x60
DATA loa<>+1(SB)/1, $0x60
DATA loa<>+2(SB)/1, $0x60
DATA loa<>+3(SB)/1, $0x60
DATA loa<>+4(SB)/1, $0x60
DATA loa<>+5(SB)/1, $0x60
DATA loa<>+6(SB)/1, $0x60
DATA loa<>+7(SB)/1, $0x60
DATA loa<>+8(SB)/1, $0x60
DATA loa<>+9(SB)/1, $0x60
DATA loa<>+10(SB)/1, $0x60
DATA loa<>+11(SB)/1, $0x60
DATA loa<>+12(SB)/1, $0x60
DATA loa<>+13(SB)/1, $0x60
DATA loa<>+14(SB)/1, $0x60
DATA loa<>+15(SB)/1, $0x60
GLOBL loa<>(SB), RODATA|NOPTR, $16

DATA hiz<>+0(SB)/1, $0x7b
DATA hiz<>+1(SB)/1, $0x7b
DATA hiz<>+2(SB)/1, $0x7b
DATA hiz<>+3(SB)/1, $0x7b
DATA hiz<>+4(SB)/1, $0x7b
DATA hiz<>+5(SB)/1, $0x7b
DATA hiz<>+6(SB)/1, $0x7b
DATA hiz<>+7(SB)/1, $0x7b
DATA hiz<>+8(SB)/1, $0x7b
DATA hiz<>+9(SB)/1, $0x7b
DATA hiz<>+10(SB)/1, $0x7b
DATA hiz<>+11(SB)/1, $0x7b
DATA hiz<>+12(SB)/1, $0x7b
DATA hiz<>+13(SB)/1, $0x7b
DATA hiz<>+14(SB)/1, $0x7b
DATA hiz<>+15(SB)/1, $0x7b
GLOBL hiz<>(SB), RODATA|NOPTR, $16

DATA c20<>+0(SB)/1, $0x20
DATA c20<>+1(SB)/1, $0x20
DATA c20<>+2(SB)/1, $0x20
DATA c20<>+3(SB)/1, $0x20
DATA c20<>+4(SB)/1, $0x20
DATA c20<>+5(SB)/1, $0x20
DATA c20<>+6(SB)/1, $0x20
DATA c20<>+7(SB)/1, $0x20
DATA c20<>+8(SB)/1, $0x20
DATA c20<>+9(SB)/1, $0x20
DATA c20<>+10(SB)/1, $0x20
DATA c20<>+11(SB)/1, $0x20
DATA c20<>+12(SB)/1, $0x20
DATA c20<>+13(SB)/1, $0x20
DATA c20<>+14(SB)/1, $0x20
DATA c20<>+15(SB)/1, $0x20
GLOBL c20<>(SB), RODATA|NOPTR, $16

DATA loAb<>+0(SB)/1, $0x40
DATA loAb<>+1(SB)/1, $0x40
DATA loAb<>+2(SB)/1, $0x40
DATA loAb<>+3(SB)/1, $0x40
DATA loAb<>+4(SB)/1, $0x40
DATA loAb<>+5(SB)/1, $0x40
DATA loAb<>+6(SB)/1, $0x40
DATA loAb<>+7(SB)/1, $0x40
DATA loAb<>+8(SB)/1, $0x40
DATA loAb<>+9(SB)/1, $0x40
DATA loAb<>+10(SB)/1, $0x40
DATA loAb<>+11(SB)/1, $0x40
DATA loAb<>+12(SB)/1, $0x40
DATA loAb<>+13(SB)/1, $0x40
DATA loAb<>+14(SB)/1, $0x40
DATA loAb<>+15(SB)/1, $0x40
DATA loAb<>+16(SB)/1, $0x40
DATA loAb<>+17(SB)/1, $0x40
DATA loAb<>+18(SB)/1, $0x40
DATA loAb<>+19(SB)/1, $0x40
DATA loAb<>+20(SB)/1, $0x40
DATA loAb<>+21(SB)/1, $0x40
DATA loAb<>+22(SB)/1, $0x40
DATA loAb<>+23(SB)/1, $0x40
DATA loAb<>+24(SB)/1, $0x40
DATA loAb<>+25(SB)/1, $0x40
DATA loAb<>+26(SB)/1, $0x40
DATA loAb<>+27(SB)/1, $0x40
DATA loAb<>+28(SB)/1, $0x40
DATA loAb<>+29(SB)/1, $0x40
DATA loAb<>+30(SB)/1, $0x40
DATA loAb<>+31(SB)/1, $0x40
GLOBL loAb<>(SB), RODATA|NOPTR, $32

DATA hiZb<>+0(SB)/1, $0x5b
DATA hiZb<>+1(SB)/1, $0x5b
DATA hiZb<>+2(SB)/1, $0x5b
DATA hiZb<>+3(SB)/1, $0x5b
DATA hiZb<>+4(SB)/1, $0x5b
DATA hiZb<>+5(SB)/1, $0x5b
DATA hiZb<>+6(SB)/1, $0x5b
DATA hiZb<>+7(SB)/1, $0x5b
DATA hiZb<>+8(SB)/1, $0x5b
DATA hiZb<>+9(SB)/1, $0x5b
DATA hiZb<>+10(SB)/1, $0x5b
DATA hiZb<>+11(SB)/1, $0x5b
DATA hiZb<>+12(SB)/1, $0x5b
DATA hiZb<>+13(SB)/1, $0x5b
DATA hiZb<>+14(SB)/1, $0x5b
DATA hiZb<>+15(SB)/1, $0x5b
DATA hiZb<>+16(SB)/1, $0x5b
DATA hiZb<>+17(SB)/1, $0x5b
DATA hiZb<>+18(SB)/1, $0x5b
DATA hiZb<>+19(SB)/1, $0x5b
DATA hiZb<>+20(SB)/1, $0x5b
DATA hiZb<>+21(SB)/1, $0x5b
DATA hiZb<>+22(SB)/1, $0x5b
DATA hiZb<>+23(SB)/1, $0x5b
DATA hiZb<>+24(SB)/1, $0x5b
DATA hiZb<>+25(SB)/1, $0x5b
DATA hiZb<>+26(SB)/1, $0x5b
DATA hiZb<>+27(SB)/1, $0x5b
DATA hiZb<>+28(SB)/1, $0x5b
DATA hiZb<>+29(SB)/1, $0x5b
DATA hiZb<>+30(SB)/1, $0x5b
DATA hiZb<>+31(SB)/1, $0x5b
GLOBL hiZb<>(SB), RODATA|NOPTR, $32

DATA loab<>+0(SB)/1, $0x60
DATA loab<>+1(SB)/1, $0x60
DATA loab<>+2(SB)/1, $0x60
DATA loab<>+3(SB)/1, $0x60
DATA loab<>+4(SB)/1, $0x60
DATA loab<>+5(SB)/1, $0x60
DATA loab<>+6(SB)/1, $0x60
DATA loab<>+7(SB)/1, $0x60
DATA loab<>+8(SB)/1, $0x60
DATA loab<>+9(SB)/1, $0x60
DATA loab<>+10(SB)/1, $0x60
DATA loab<>+11(SB)/1, $0x60
DATA loab<>+12(SB)/1, $0x60
DATA loab<>+13(SB)/1, $0x60
DATA loab<>+14(SB)/1, $0x60
DATA loab<>+15(SB)/1, $0x60
DATA loab<>+16(SB)/1, $0x60
DATA loab<>+17(SB)/1, $0x60
DATA loab<>+18(SB)/1, $0x60
DATA loab<>+19(SB)/1, $0x60
DATA loab<>+20(SB)/1, $0x60
DATA loab<>+21(SB)/1, $0x60
DATA loab<>+22(SB)/1, $0x60
DATA loab<>+23(SB)/1, $0x60
DATA loab<>+24(SB)/1, $0x60
DATA loab<>+25(SB)/1, $0x60
DATA loab<>+26(SB)/1, $0x60
DATA loab<>+27(SB)/1, $0x60
DATA loab<>+28(SB)/1, $0x60
DATA loab<>+29(SB)/1, $0x60
DATA loab<>+30(SB)/1, $0x60
DATA loab<>+31(SB)/1, $0x60
GLOBL loab<>(SB), RODATA|NOPTR, $32

DATA hizb<>+0(SB)/1, $0x7b
DATA hizb<>+1(SB)/1, $0x7b
DATA hizb<>+2(SB)/1, $0x7b
DATA hizb<>+3(SB)/1, $0x7b
DATA hizb<>+4(SB)/1, $0x7b
DATA hizb<>+5(SB)/1, $0x7b
DATA hizb<>+6(SB)/1, $0x7b
DATA hizb<>+7(SB)/1, $0x7b
DATA hizb<>+8(SB)/1, $0x7b
DATA hizb<>+9(SB)/1, $0x7b
DATA hizb<>+10(SB)/1, $0x7b
DATA hizb<>+11(SB)/1, $0x7b
DATA hizb<>+12(SB)/1, $0x7b
DATA hizb<>+13(SB)/1, $0x7b
DATA hizb<>+14(SB)/1, $0x7b
DATA hizb<>+15(SB)/1, $0x7b
DATA hizb<>+16(SB)/1, $0x7b
DATA hizb<>+17(SB)/1, $0x7b
DATA hizb<>+18(SB)/1, $0x7b
DATA hizb<>+19(SB)/1, $0x7b
DATA hizb<>+20(SB)/1, $0x7b
DATA hizb<>+21(SB)/1, $0x7b
DATA hizb<>+22(SB)/1, $0x7b
DATA hizb<>+23(SB)/1, $0x7b
DATA hizb<>+24(SB)/1, $0x7b
DATA hizb<>+25(SB)/1, $0x7b
DATA hizb<>+26(SB)/1, $0x7b
DATA hizb<>+27(SB)/1, $0x7b
DATA hizb<>+28(SB)/1, $0x7b
DATA hizb<>+29(SB)/1, $0x7b
DATA hizb<>+30(SB)/1, $0x7b
DATA hizb<>+31(SB)/1, $0x7b
GLOBL hizb<>(SB), RODATA|NOPTR, $32

DATA c20b<>+0(SB)/1, $0x20
DATA c20b<>+1(SB)/1, $0x20
DATA c20b<>+2(SB)/1, $0x20
DATA c20b<>+3(SB)/1, $0x20
DATA c20b<>+4(SB)/1, $0x20
DATA c20b<>+5(SB)/1, $0x20
DATA c20b<>+6(SB)/1, $0x20
DATA c20b<>+7(SB)/1, $0x20
DATA c20b<>+8(SB)/1, $0x20
DATA c20b<>+9(SB)/1, $0x20
DATA c20b<>+10(SB)/1, $0x20
DATA c20b<>+11(SB)/1, $0x20
DATA c20b<>+12(SB)/1, $0x20
DATA c20b<>+13(SB)/1, $0x20
DATA c20b<>+14(SB)/1, $0x20
DATA c20b<>+15(SB)/1, $0x20
DATA c20b<>+16(SB)/1, $0x20
DATA c20b<>+17(SB)/1, $0x20
DATA c20b<>+18(SB)/1, $0x20
DATA c20b<>+19(SB)/1, $0x20
DATA c20b<>+20(SB)/1, $0x20
DATA c20b<>+21(SB)/1, $0x20
DATA c20b<>+22(SB)/1, $0x20
DATA c20b<>+23(SB)/1, $0x20
DATA c20b<>+24(SB)/1, $0x20
DATA c20b<>+25(SB)/1, $0x20
DATA c20b<>+26(SB)/1, $0x20
DATA c20b<>+27(SB)/1, $0x20
DATA c20b<>+28(SB)/1, $0x20
DATA c20b<>+29(SB)/1, $0x20
DATA c20b<>+30(SB)/1, $0x20
DATA c20b<>+31(SB)/1, $0x20
GLOBL c20b<>(SB), RODATA|NOPTR, $32

