//go:build ppc64le

package ascii

// VSX kernels (16-byte stride) generated by go-asmgen (ascii_ppc64le_gen.go), in
// ascii_ppc64le.s. the SIMD path is the arch's only path (build-tagged); no runtime
// feature check is needed.
func lowerBlocks(dst, src []byte, n int)
func upperBlocks(dst, src []byte, n int)
func equalFoldBlocks(a, b []byte, n int) int

func lowerSIMD(dst, src []byte) int {
	if n := len(src); n >= 16 {
		blocks := n / 16
		lowerBlocks(dst, src, blocks)
		return blocks * 16
	}
	return 0
}

func upperSIMD(dst, src []byte) int {
	if n := len(src); n >= 16 {
		blocks := n / 16
		upperBlocks(dst, src, blocks)
		return blocks * 16
	}
	return 0
}

func equalFoldSIMD(a, b []byte) int {
	if n := len(a); n >= 16 {
		blocks := n / 16
		if equalFoldBlocks(a, b, blocks) == 0 {
			return -1
		}
		return blocks * 16
	}
	return 0
}
