// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·lowerBlocks(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R1
	MOVD src_base+24(FP), R2
	MOVD n+48(FP), R3
	VREPIB $65, V20
	VREPIB $91, V21
	VREPIB $128, V22
	CMPBEQ R3, $0, done
loop:
	VL (R2), V0
	VSB V20, V0, V1
	VN V22, V1, V1
	VX V22, V1, V1
	VSB V21, V0, V2
	VN V22, V2, V2
	VN V1, V2, V2
	VESRLB $2, V2, V2
	VAB V2, V0, V0
	VST V0, (R1)
	ADD $16, R2
	ADD $16, R1
	ADD $-1, R3
	CMPBNE R3, $0, loop
done:
	RET

TEXT ·upperBlocks(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R1
	MOVD src_base+24(FP), R2
	MOVD n+48(FP), R3
	VREPIB $97, V20
	VREPIB $123, V21
	VREPIB $128, V22
	CMPBEQ R3, $0, done
loop:
	VL (R2), V0
	VSB V20, V0, V1
	VN V22, V1, V1
	VX V22, V1, V1
	VSB V21, V0, V2
	VN V22, V2, V2
	VN V1, V2, V2
	VESRLB $2, V2, V2
	VSB V2, V0, V0
	VST V0, (R1)
	ADD $16, R2
	ADD $16, R1
	ADD $-1, R3
	CMPBNE R3, $0, loop
done:
	RET

TEXT ·equalFoldBlocks(SB), NOSPLIT, $0-64
	MOVD a_base+0(FP), R1
	MOVD b_base+24(FP), R2
	MOVD n+48(FP), R3
	VREPIB $65, V20
	VREPIB $91, V21
	VREPIB $128, V22
	VZERO V24
	CMPBEQ R3, $0, fdone
floop:
	VL (R1), V3
	VSB V20, V3, V1
	VN V22, V1, V1
	VX V22, V1, V1
	VSB V21, V3, V2
	VN V22, V2, V2
	VN V1, V2, V2
	VESRLB $2, V2, V2
	VAB V2, V3, V3
	VL (R2), V4
	VSB V20, V4, V1
	VN V22, V1, V1
	VX V22, V1, V1
	VSB V21, V4, V2
	VN V22, V2, V2
	VN V1, V2, V2
	VESRLB $2, V2, V2
	VAB V2, V4, V4
	VX V4, V3, V3
	VO V3, V24, V24
	ADD $16, R1
	ADD $16, R2
	ADD $-1, R3
	CMPBNE R3, $0, floop
fdone:
	VLGVG $0, V24, R5
	VLGVG $1, V24, R6
	OR R6, R5
	MOVD $1, R7
	CMPBEQ R5, $0, fret
	MOVD $0, R7
fret:
	MOVD R7, ret+56(FP)
	RET

